### ISSUE TITLE
Bad merge conflict resolution on chain_events documentation?  Might be time to regenerate build artifacts and redeploy?

### ISSUE THREAD

**Issue by aallbrig** [netbeast/docs#11]
Hey, exciting project!  I was reading through the documentation and found what I believe are artifacts of a bad conflict resolution.  You can see what I'm talking about on this page: http://docs.netbeast.co/chapters/api_reference/chain_events.html  (Specifically `<<<<<<< HEAD` and `=======` and `master`).

When I was looking through source, I found the offending text here (https://github.com/netbeast/docs/blob/29a3e4dea82ac87ff119b8367417d150d30b421d/_book/chapters/api_reference/chain_events.html#L649) and here (https://github.com/netbeast/docs/blob/29a3e4dea82ac87ff119b8367417d150d30b421d/_book/chapters/api_reference/chain_events.html#L649).

Digging a little deeper, I found that this was indeed something taken out as a part of this merge (https://github.com/netbeast/docs/commit/5c717a683288b623e8f6f51f102c2435e67ad396#diff-ea499b9193379729eaba076c2fa353fcL16) and what I may have seen are the artifacts of the build system (?)

So with these pieces of information it seems that the correct course of action would be to generate new build artifacts from source and redeploy, as the problem has already been fixed.

**Comment by aallbrig** [comment]
Looks like `_book` directory is the build dir.  The `_book` directory was added to `.gitignore`, source was changed, but build artifacts were not.

I don't know the ramifications of this, but if you use `git add _book -f` you can add the `_book` build files once again.

Another solution would be to remove `_book` from `.gitignore`, add the files, then add `_book` back to `.gitignore`.

The better answer might be to not version the build files, and always build at deploy time.

At any rate, it's time for work!

**Comment by jsdario** [comment]
You are absolutely right! However `_book` was intentionally ignored. The book is being built on http://gitbook.com site (great place to work on your docs), and only will be rebuilt if we are going to publish in, e.g: http://netbeast.gihub.io/docs, which we could shortly.

The fail was result from a miscommit / mispush and can be fixed individually. By redeploying indeed. If there are any more pages with this bug please tell! I redeployed and hopefully it is OK now.

If you want to learn more about the build system, take a look on https://github.com/GitbookIO/gitbook#getting-started 

Thanks for the feedback ??

[--- Commented from Asana.com
#commenter jsdario
---[aa]

**Comment by aallbrig** [comment]
@jsdario Glad to see that it's been fixed on the live site!

Since `_book` was indeed added to `.gitignore` intentionally, might it also be worth it to remove the artifacts from version control as well?  This morning I had suspected there may have been a reason that it was VC'd but you've hinted at there not being one.  Looks like a simple `git rm -r --cached _book` would do the trick, here.

**Comment by jsdario** [comment]
Seems that our publisher (gitbook) is not storing properly `_book` commits and making it a little difficult, so could be for the best interest to remove effectively `_book` from `.gitignore` and solve merging conflicts properly, indeed.

**Comment by jsdario** [comment]
Thanks @aallbrig for your collaboration, our docs have been finally updated! 🚀
