### ISSUE TITLE
Documentation for NPM module cross compilation

### ISSUE THREAD

**Issue by sdesalas** [netbeast/docs#21]
Hiya, 

I just thought you'd like to know that I followed the steps in your documentation (very useful by the way):

https://github.com/netbeast/docs/wiki/Cross-Compile-NPM-modules

And I found that I could only compile my package if the switch `--target_arch=<name>` was used instead of `--arch=<name>` in the section below:

* Secondly, create a folder for your npm module and run:

```
cd folder_name
npm --arch=<name> install <npm module>
```

* If all went well, you will have your npm module cross-compiled.

**Comment by jsdario** [comment]
Hi @sdesalas, thanks so much.
Maybe the internal API changed and the documentation became obsolete, I'll fix it!

EDIT: done! https://github.com/netbeast/docs/wiki/Cross-Compile-NPM-modules
